In [1]:
data = {
    "name":  ["Alice", "Bob", "Clara", "David", "Eva"],
    "age":   [21, 25, 22, 19, 23],
    "score": [85, 90, 91, 76, 60],
    "city":  ["Delhi", "Mumbai", "Delhi", "Chennai", "Mumbai"]
}

In [2]:
import pandas as pd

df = pd.DataFrame(data)

print(df)

    name  age  score     city
0  Alice   21     85    Delhi
1    Bob   25     90   Mumbai
2  Clara   22     91    Delhi
3  David   19     76  Chennai
4    Eva   23     60   Mumbai

In [3]:
df.shape

(5, 4)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      object
 1   age     5 non-null      int64
 2   score   5 non-null      int64
 3   city    5 non-null      object
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes

In [ ]:
# Selecting columns

print(df["name"])
print(df[["name","age"]])

0    Alice
1      Bob
2    Clara
3    David
4      Eva
Name: name, dtype: object
    name  age
0  Alice   21
1    Bob   25
2  Clara   22
3  David   19
4    Eva   23

In [ ]:
# Selecting rows

print(df.iloc[0])
print(df.iloc[0:3])

name     Alice
age         21
score       85
city     Delhi
Name: 0, dtype: object
    name  age  score    city
0  Alice   21     85   Delhi
1    Bob   25     90  Mumbai
2  Clara   22     91   Delhi

In [16]:
# Filtering rows

print(df[df["score"]>80])

print(df[df["city"]=="Mumbai"])

print(df[(df["age"]>22) & (df["score"]>70)])

    name  age  score    city
0  Alice   21     85   Delhi
1    Bob   25     90  Mumbai
2  Clara   22     91   Delhi
  name  age  score    city
1  Bob   25     90  Mumbai
4  Eva   23     60  Mumbai
  name  age  score    city
1  Bob   25     90  Mumbai

In [ ]:
# Sorting

df.sort_values("age", ascending=False)

    name  age  score     city
1    Bob   25     90   Mumbai
4    Eva   23     60   Mumbai
2  Clara   22     91    Delhi
0  Alice   21     85    Delhi
3  David   19     76  Chennai

In [20]:
# Adding New column with Grades

df["grade"] = df["score"].apply(lambda x: "A" if x >= 90 else "B" if x>=80 else "C" if x>=70 else "F")

In [21]:
df.head()

    name  age  score     city grade
0  Alice   21     85    Delhi     B
1    Bob   25     90   Mumbai     A
2  Clara   22     91    Delhi     A
3  David   19     76  Chennai     C
4    Eva   23     60   Mumbai     F